// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chat.sql

package database

import (
	"context"
)

const getAllChats = `-- name: GetAllChats :many
SELECT id, name, created_at, updated_at FROM chats
`

func (q *Queries) GetAllChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getAllChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
